# Generated by Django 3.0.2 on 2020-03-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200320_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
