# Generated by Django 3.0.2 on 2020-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='very fun time', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='num_attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='over zoom :(', max_length=150),
        ),
    ]
