# Generated by Django 3.0.2 on 2020-03-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200326_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='profile_pics/unknown.png', upload_to='profile_pics'),
        ),
    ]
