# Generated by Django 3.0.2 on 2020-03-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_nopes',
            field=models.IntegerField(default=0),
        ),
    ]
