# Generated by Django 3.0.2 on 2020-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='unknown.png', upload_to='profile_pics'),
        ),
    ]
