# Generated by Django 3.0.2 on 2020-03-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200320_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/unknown.png', upload_to='profile_pics'),
        ),
    ]
